# Homework 1

**Course:** MATH 6388

**Author:** Brady Lamson

**Date:** 8/25/2026

---

## Imports

In [1]:
import torch
from torch import linalg as LA

## Problem 1.1

Suppose a weather station records temperature, humidity, and wind speed every hour for 7 consecutive days. The data is stored in a PyTorch tensor, where:

- Axis 0 represents the day.
- Axis 1 represents the weather variable (0 = Temperature, 1 = Humidity, 2 = Wind Speed).
- Axis 2 represents the hour of the day (0–23).

```
# Generate random weather data
torch.manual_seed(42)
weather = torch.rand(7, 3, 24)
```

- What is the shape of the weather tensor?
- Print all weather measurements (temperature, humidity, and wind speed) for Day 4.
- Print the temperature recorded at 2:00 PM on Day 6.

In [2]:
torch.manual_seed(42)
weather = torch.rand(7, 3, 24)

# 1.1.1
print(f"1. Overall shape:\n{weather.shape}")

# 1.1.2
print(f"\n2. All measurement on Day 4:")
# Axis labels for printing purposes, purely a convenience thing
axis_1_labels = {
    0: "Temperature",
    1: "Humidity",
    2: "Wind Speed"
}
day = 4
for i, measurements in enumerate(weather[day - 1]):
    print(f"{axis_1_labels[i]} Measurements:")
    print(f"   {measurements}")

# 1.1.3
# Assuming the time axis works like military time, where 23:00 is 11pm
# Here the 0 index would be midnight, 1 index is 1am and so on
# In this case, 2pm is index 14
day = 6
print(f"\n3. Temperature at 2pm on Day 6:\n{weather[day - 1, 0, 14]}")

1. Overall shape:
torch.Size([7, 3, 24])

2. All measurement on Day 4:
Temperature Measurements:
   tensor([0.5723, 0.3705, 0.7069, 0.3096, 0.1764, 0.8649, 0.2726, 0.3998, 0.0026,
        0.8346, 0.8788, 0.6822, 0.1514, 0.0065, 0.0939, 0.8729, 0.7401, 0.9208,
        0.7619, 0.6265, 0.4951, 0.1197, 0.0716, 0.0323])
Humidity Measurements:
   tensor([0.7047, 0.2545, 0.3994, 0.2122, 0.4089, 0.1481, 0.1733, 0.6659, 0.3514,
        0.8087, 0.3396, 0.1332, 0.4118, 0.2576, 0.3470, 0.0240, 0.7797, 0.1519,
        0.7513, 0.7269, 0.8572, 0.1165, 0.8596, 0.2636])
Wind Speed Measurements:
   tensor([0.6855, 0.9696, 0.4295, 0.4961, 0.3849, 0.0825, 0.7400, 0.0036, 0.8104,
        0.8741, 0.9729, 0.3821, 0.0892, 0.6124, 0.7762, 0.0023, 0.3865, 0.2003,
        0.4563, 0.2539, 0.2956, 0.3413, 0.0248, 0.9103])

3. Temperature at 2pm on Day 6:
0.1314082145690918


## 1.2

Recall that the angle $\theta$ between two vectors $\mathbf{x}$ and $\mathbf{y}$ is given by

$$
\cos(\theta)=
\frac{\mathbf{x}\cdot\mathbf{y}}
{\|\mathbf{x}\|\,\|\mathbf{y}\|}
$$

where:

- $\mathbf{x}\cdot\mathbf{y}$ is the dot product of the vectors.
- $\|\mathbf{x}\|$ and $\|\mathbf{y}\|$ are their Euclidean (L2) norms.

Write a Python function named `vector_angle()` that computes the angle (in degrees) between two 1D PyTorch tensors.

### Answer

Only a few things to explain here. The function we write really just recreates this equation, mostly.

The dot product is straightforward enough. For the L2 norms we can simply use `torch.linalg.vector_norm`.

Where it gets tricky is that we want the angle in degrees. This equation gives us $\cos(\theta)$ where $\theta$ is in radians. So we need to use inverse cosine and then convert from radians to degrees. This is an easy part to miss. Thankfully the torch library makes that easy for us.

In [4]:
def vector_angle(
        x: torch.Tensor,
        y: torch.Tensor
) -> torch.Tensor:
    xdoty = torch.dot(x, y)
    xnorm = LA.vector_norm(x)
    ynorm = LA.vector_norm(y)
    cos_theta = xdoty / (xnorm * ynorm)
    theta_radians = torch.acos(cos_theta)
    theta_degrees = torch.rad2deg(theta_radians)

    return theta_degrees

# Make sure the function works as intended
x = torch.tensor([0.0, 1.0])
y = torch.tensor([-1.0, 1.0])
angle = vector_angle(x, y)
print(f"Angle: {angle:.2f} degrees")

Angle: 45.00 degrees
